[terminal.shell]
program = "/usr/bin/fish"
args = ["-l"]

[window]
# Window size
dimensions = { columns = 100, lines = 30 }
# Window startup position
position = { x = 600, y = 200 }
# Background opacity
opacity = 0.9

[scrolling]
history = 2000
multiplier = 10

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 12

[keyboard]
bindings = [
    # https://stackoverflow.com/questions/16359878/how-to-map-shift-enter/42461580#42461580
    { key = "Return", mods = "Shift", chars = "\u001B[13;2u" }
]

