[shell]
program = "/usr/local/bin/fish" 
args = ["-l"]

[window]
# Window size
dimensions = { columns = 100, lines = 30 }
# Window startup position
position = { x = 600, y = 200 }
# Background opacity
opacity = 0.6

[scrolling]
history = 2000
multiplier = 10

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 12

