[manager]
prepend_keymap = [
  { on = [ "l" ], run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
]
append_keymap = [
]

[input]
prepend_keymap = [
  { on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
]


[plugin]
prepend_previewers = [
]

