[manager]
prepend_keymap = [
  { on = [ "l" ], exec = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
]
append_keymap = [
]

[input]
prepend_keymap = [
  { on = [ "<Esc>" ], exec = "close", desc = "Cancel input" },
]


[plugin]
prepend_previewers = [
]

