[opener]
edit = [
    { exec = '${EDITOR:=nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
open = [
    { exec = 'xdg-open "$@"',                desc = "Open", for = "linux" },
]
reveal = [
    { exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
    { exec = 'unar "$1"', desc = "Extract here", for = "unix" },
]
play = [
    { exec = 'mpv "$@"', orphan = true, for = "unix" },
    { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]
pdfview = [
    { exec = 'zathura "$@"', orphan = true, desc = "Open PDF file", for = "linux" },
]
wpsopen = [
    { exec = 'wps "$@"', orphan = true, desc = "WPS for word, xls, ppt, and pdf.", for = "linux" },
]

[open]
rules = [
    { mime = "text/*", use = [ "edit", "reveal" ]},
    { mime = "image/*", use = [ "open", "reveal" ]},
    { mime = "video/*", use = [ "play", "reveal" ]},
    
    { mime = "application/pdf", use = [ "pdfview", "wpsopen"] },
    { name = "*.doc", use = "wpsopen" },
    { name = "*.docx", use = "wpsopen" },
    { name = "*.xls", use = "wpsopen" },
    { name = "*.ppt", use = "wpsopen" },
    { name = "*.pptx", use = "wpsopen" },
]
